# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8456bd6177bf40828e560bdf84f4e0e8a42a9d3058f12fa433ea618533fa7edd306d667113c646004a0459f99e33fed45805146aa5d1bf709d58f77ec379c0de

test:
  secret_key_base: 93c355a49db2e75ea98500b68cf11cfcd3918ba93ad3b246715b5cc35d5ef1f6298da93641f45075f367f6c295eb38e0f4f9b009985611cb30138efa5d14ffce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
